### ISSUE TITLE
Github Action - Usage

### ISSUE THREAD

**Issue by phac008** [suxess-it/kubriX#194]
<img width="670" alt="Bildschirmfoto 2024-05-29 um 07 12 14" src="https://github.com/suxess-it/sx-cnp-oss/assets/112545451/12ac15ef-67a3-4791-96a8-0698531dad4a">

Fresh Actions next week - may be an issue in future?

**Comment by jkleinlercher** [comment]
this relates to the private repository sx-backstage .
Either we can reduce the build time for backstage or we make the repository public.
