### ISSUE TITLE
[cnpg] cluster resource out of sync 

### ISSUE THREAD

**Issue by phac008** [suxess-it/kubriX#898]
missing:
    pg_hba: []
    pg_ident: []

https://github.com/cloudnative-pg/charts/issues/426

**Comment by jkleinlercher** [comment]
I implemented this workaround in a customers argocd values file:

```yaml
      resource.customizations.ignoreDifferences.postgresql.cnpg.io_Cluster: |
        jqPathExpressions:
          - '.spec.postgresql.pg_hba'
          - '.spec.postgresql.pg_ident'
```

**Comment by jkleinlercher** [comment]
I needed to implement it also here https://github.com/kubriX-demo/kubriX-demo-prime-dt/pull/12

**Comment by jkleinlercher** [comment]
> I implemented this workaround in a customers argocd values file:
> 
> ```yaml
>       resource.customizations.ignoreDifferences.postgresql.cnpg.io_Cluster: |
>         jqPathExpressions:
>           - '.spec.postgresql.pg_hba'
>           - '.spec.postgresql.pg_ident'
> ```

This workaround fixed the problem
